2023-05-03 18:12:17.262 [info] Log level: Info
2023-05-03 18:12:17.262 [info] Validating found git in: "git"
2023-05-03 18:12:17.262 [info] Using git "2.25.1" from "git"
2023-05-03 18:12:17.265 [info] > git rev-parse --show-toplevel [26ms]
2023-05-03 18:12:17.265 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:12:17.295 [info] > git rev-parse --show-toplevel [24ms]
2023-05-03 18:12:17.295 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:12:17.302 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:12:17.302 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:12:17.308 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:12:17.308 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:12:20.568 [info] > git rev-parse --show-toplevel [25ms]
2023-05-03 18:12:20.568 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:12:29.637 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:12:29.637 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:12:31.970 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:12:31.970 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:14:36.899 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:14:36.899 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:15:51.733 [info] > git rev-parse --show-toplevel [3ms]
2023-05-03 18:15:51.733 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:15:53.027 [info] > git rev-parse --show-toplevel [5ms]
2023-05-03 18:15:53.027 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:15:54.027 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:15:54.027 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:16:02.084 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:16:02.084 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:16:07.058 [info] > git rev-parse --show-toplevel [225ms]
2023-05-03 18:16:07.058 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:16:11.152 [info] > git rev-parse --show-toplevel [15ms]
2023-05-03 18:16:11.152 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:16:19.592 [info] > git rev-parse --show-toplevel [3ms]
2023-05-03 18:16:19.592 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:17:07.820 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:17:07.820 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:18:11.051 [info] > git rev-parse --show-toplevel [3ms]
2023-05-03 18:18:11.051 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:18:20.060 [info] > git rev-parse --show-toplevel [2ms]
2023-05-03 18:18:20.060 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:18:21.953 [info] > git rev-parse --show-toplevel [100ms]
2023-05-03 18:18:21.953 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:18:44.856 [info] > git rev-parse --show-toplevel [3ms]
2023-05-03 18:18:44.856 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:18:45.560 [info] > git rev-parse --show-toplevel [8ms]
2023-05-03 18:18:45.560 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
2023-05-03 18:18:50.947 [info] > git rev-parse --show-toplevel [3ms]
2023-05-03 18:18:50.947 [info] fatal: detected dubious ownership in repository at '/home/projeto_exemplo_python/python-getting-started'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/projeto_exemplo_python/python-getting-started
